//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandmarkRemark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remark
    {
        public int RemarkId { get; set; }
        public int UserId { get; set; }
        public string RemarkText { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual User User { get; set; }
    }
}
